# Generated by Django 3.1.5 on 2021-01-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='dt_criação',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
